server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5555/demodb
spring.datasource.username=demo
spring.datasource.password=demo123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database=POSTGRESQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
