server.port=8090
spring.application.name=demo-app
spring.datasource.url=jdbc:postgresql://localhost:5555/demodb
spring.datasource.username=demo
spring.datasource.password=demo123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database=POSTGRESQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
## Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.password=redis123
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
# Spring Session
spring.session.store-type=redis
spring.session.timeout=1800s
spring.session.redis.namespace=demo:sessions
# config ELK
spring.profiles.active=local