apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hello
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-hello
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-hello
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-hello
    spec:
      containers:
        - name: hello
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
